{{- range .Values.vms }}
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ required "vm.name is required" .name }}-boot
  namespace: {{ required "namespace is required" $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  sourceRef:
    kind: DataSource
    name: {{ required "image.dataSourceName is required" $.Values.image.dataSourceName }}
    namespace: {{ required "image.dataSourceNamespace is required" $.Values.image.dataSourceNamespace }}
  storage:
    accessModes:
      - ReadWriteOnce
    {{- if $.Values.storage.className }}
    storageClassName: {{ $.Values.storage.className }}
    {{- end }}
    resources:
      requests:
        storage: {{ $.Values.storage.size }}
{{- end }}
